check:
  - overlays-build
overlays_dir: overlays
overlays:
  - name: python36
    build:
      build-stratergy: Dockerfile
      registry: "quay.io"
      registry-org: "thoth-station"
      registry-project: "s2i-minimal-notebook"
      registry-secret: "thoth-station-thoth-pusher-secret"

  - name: python38
    build:
      build-stratergy: Dockerfile
      registry: "quay.io"
      registry-org: "thoth-station"
      registry-project: "s2i-minimal-py38-notebook"
      registry-secret: "thoth-station-thoth-pusher-secret"
